#!/bin/bash

set -e

#
# When Startup Container script
#




if [[ -e /scripts/firstrun ]]; then
        # config mysqldb
        /scripts/firstrun_mysql
        rm /scripts/firstrun
else
        # Cleanup previous mysqldb sockets
        if [[ -e ${DATA_DIR}/mysql.sock ]]; then
                rm -f ${DATA_DIR}/mysql.sock
        fi
fi

exec "$@"
