#!/bin/bash

DB_USER=${DB_USER:-foxchan}
DB_PASS=${DB_PASS:-emar}

MYSQLDB_NEW=true

#
#  MYSQLDB setup #
#
firstrun_mysql() {

        # First install mysqldb
        if [[ ! -d ${DATA_DIR}/mysql ]]; then 
	echo "===> MYSQLDB not install..."

        echo "===> Initializing mysql database... "
                mysql_install_db  --user=mysql
        echo "===> System databases initialized..."

                # Start mysqldb
	mysqld_safe > /dev/null 2>&1 &

        echo "===> Waiting for MysqlDB to start..."

                STA=1
                while [[ STA -ne 0 ]]; do
            printf "."
                        sleep 5
                        mysql -uroot -e "status" > /dev/null 2>&1
                        STA=$?
                done
        echo "===> Start OK..."

                # 1. Create a localhost-only admin account
                mysql -u root -e "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS'"
                mysql -u root -e "CREATE USER '$DB_USER'@'127.0.0.1' IDENTIFIED BY '$DB_PASS'"
                mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'%' WITH GRANT OPTION"
        echo "===> Create localhost completed..."

                # shutdown mysqldb to wait for supervisor
                mysqladmin -u root shutdown

        else
        if [[ -e ${WORKDIR}/mysql.sock ]]; then
            rm -f ${WORKDIR}/mysql.sock
        fi 
        
	MYSQLDB_NEW=false 

		echo "===> Using an existing volume of MysqlDB"
        fi
}


firstrun_mysql
